export const products = [
    {
      id: 1,
      name: "Lenovo IdeaPad 3 14ITL6",
      category: "Laptop",
      price: 504,
      image: "/images/l1.png",
      isCart: false,
      description: "Intel Core i3-1115G4 || Integrated Intel UHD Graphics || 8GB Soldered DDR4-3200 || Memory Slots: One memory soldered to systemboard, one DDR4 SO-DIMM slot, dual-channel capable ||  512GB SSD M.2 2280 PCIe 3.0x4 NVMe || Camera 720p with Privacy Shutter || 14* FHD (1920x1080) TN 250nits Anti-glare, 45% NTSC.",
    },
    {
      id: 2,
      name: "Acer Aspire 5 (Ryzen 5000) A515-45",
      category: "Laptop",
      price: 410,
      image: "/images/l2.png",
      isCart: false,
      description: "AMD Ryzen 3 5300U Quad Core clock up to 3.8 GHz || 8GB DDR4 || SSD 512 GB || TFT LCD 15.6 inci HD 1366 x 768 piksel HD 720p || Baterai: Li-Ion 45Wh || Port: HDMI, USB 3.2, USB 2.0, LAN RJ45, Audio Jack 3.5 mm || Speaker: 2x Speaker Stereo || Konektivitas: WiFi Dual Band, Bluetooth 5.1.",
    },
    {
      id: 3,
      name: "HP Laptop 15s-fq2503TU",
      category: "Laptop",
      price: 454,
      image: "/images/l3.png",
      isCart: false,
      description: "Intel Core i3-1115G4 Dual Core clock up to 4.1 GHz || Intel UHD Graphics || 8GB DDR4 || SSD 512 GB || IPS LCD 15.6 inci FHD 1920 x 1080 piksel HD 720p || Baterai: Li-Ion 41Wh || 2x Speaker Stereo || Port: HDMI, USB 3.0, Audio Jack 3.5 mm || Konektivitas: WiFi Dual Band, Bluetooth 4.2.",
    },
    {
      id: 4,
      name: "OPPO Reno8",
      category: "Hp",
      price: 441,
      image: "/images/oppor8.png",
      isCart: false,
      description: "RAM & ROM 8GB + 256GB LPDDR4X @ 2133MHz 2×16bit || Qualcomm® Snapdragon™ 680 || 6,43 inci (16,33 cm) || FHD+ (2400x1080) || Refresh Rate 90 Hz || Kamera utama 64MP, f/1.7; 79° FOV; lensa 6P; AF; motor fokus loop terbuka yang digunakan | Kamera makro: 2MP, f/3.3; 65 ° FOV; lensa 3P+IR; FF | Kamera mono: 2MP, f/2.4; 89° FOV; lensa 3P+IR; FF || EIS: 1080p pada 30 fps atau 720p pada 30 fps.      ",
    },
    {
      id: 5,
      name: "Oppo Reno9",
      category: "Hp",
      price: 454,
      image: "/images/oppor9.png",
      isCart: false,
      description: "RAM/ROM 12GB 512GB || Qualcomm SM7325 Snapdragon 778G 5G (6 nm) || Octa-core (1x2.4 GHz Cortex-A78 & 3x2.2 GHz Cortex-A78 & 4x1.9 GHz Cortex-A55) ||  Dual SIM (Nano-SIM, dual stand-by) || AMOLED, 1B colors, 120Hz, HDR10+, 500 nits (typ), 800 nits (HBM), 950 nits || NETWORK Technology GSM / CDMA / HSPA / CDMA2000 / LTE / 5G.",
    },
    {
        id: 6,
        name: "Line follower robot",
        category: "robot",
        image: "/images/rbl.jpg",
        isCart: false,
        description: "Line follower robot adalah sebuah robot yang dapat mengikuti garis secara otomatis. Robot didukung oleh rangkain komponen elektronika yang dilengkapi dengan roda dan digerakan oleh motor. Pengendalian kecepatan sangat bergantung pada batas putaran dan pergesekan antara ban robot dengan lantainya. Robot tersebut dirancang untuk bernavigasi dan bergerak secara otomatis mengikuti sebuah alur garis yang dibuat.",
      },
      {
        id: 7,
        name: "Human Follower Robot",
        category: "robot",
        image: "/images/rbh.jpg",
        isCart: false,
        description: "Robot Arduino ini memiliki sensor yang dapat mendeteksi objek apa pun di dekatnya dan dapat mengikuti objek tersebut. jika Anda berada di depan robot, robot itu akan mulai mengikuti Anda. robot ini terdiri dari sensor ultrasonik dan sensor IR yang membantu mengikuti objek. ini mirip dengan robot penghindar rintangan saja tetapi cara kerjanya berlawanan. robot pengikut manusia adalah yang terbaik dalam proyek saat ini. Anda dapat membuat robot luar biasa ini dengan yang diberikan.",
      },
      {
        id: 8,
        name: "Tab S9FE+",
        category: "Tab",
        price: 536,
        image: "/images/st2.png",
        isCart: false,
        description: "Lihat konten, buat, dan mainkan selama Anda suka, ketahuilah bahwa mata Anda terlindungi dengan baik. Layar2 pada Galaxy Tab S9 FE dan Tab S9 FE+ dirancang dengan pengurangan emisi cahaya biru3 untuk melindungi penglihatan Anda, memberikan pengalaman menonton yang nyaman saat Anda berada di zona menyenangkan.",
      },
      {
        id: 9,
        name: "Wi-Fi Galaxy Tab S9 FE",
        category: "Tab",
        price: 410,
        image: "/images/st3.png",
        isCart: false,
        description: "Benamkan indra Anda dalam gambar yang halus berkat kecepatan refresh adaptif layar hingga 90Hz. Baik Anda sedang menonton serial favorit, menelusuri media sosial, atau mengedit video terbaru, layar akan menyesuaikan untuk membuat setiap gerakan terlihat lancar dan nyata.",
      }
  ];